In [1]:
import pandas, requests, datetime, calendar

class dividend_calendar:
     #class attributes 
     calendars = [] 
     url = 'https://api.nasdaq.com/api/calendar/dividends'
     hdrs =  {'Accept': 'application/json, text/plain, */*',
                 'DNT': "1",
                 'Origin': 'https://www.nasdaq.com/',
                 'Sec-Fetch-Mode': 'cors',
                 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0)'}
     def __init__(self, year, month):
          '''
        Parameters
        ----------
        year : year int
        month : month int
        
        Returns
        -------
        Sets instance attributes for year and month of object.
        
          '''
          #instance attributes
          self.year = int(year)
          self.month = int(month)


def scraper(self, date_str):
         ''' 
          Scrapes JSON object from page using requests module
           
           Parameters
           - - - - - 
           url : URL string
           hdrs : Header information
           date_str: string in yyyy-mm-dd format
               
           Returns
           - - - -
           dictionary : Returns a JSON dictionary at a given URL.
         
         '''
         params = {'date': date_str}     
         page=requests.get(self.url,headers=self.hdrs,params=params)
         dictionary = page.json()
         return dictionary

def date_str(self, day):
     date_obj = datetime.date(self.year, self.month, day)
     date_str = date_obj.strftime(format='%Y-%m-%d')     
     return date_str

In [90]:
import pandas, requests, datetime, calendar
class dividend_calendar:
    #class attributes 
    calendars = [] 
    url = 'https://api.nasdaq.com/api/calendar/dividends'
    hdrs =  {'Accept': 'application/json, text/plain, */*',
                 'DNT': "1",
                 'Origin': 'https://www.nasdaq.com/',
                 'Sec-Fetch-Mode': 'cors',
                 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0)'}

    def __init__(self, year, month):
          '''
        Parameters
        ----------
        year : year int
        month : month int
        
        Returns
        -------
        Sets instance attributes for year and month of object.
        
          '''
          #instance attributes
          self.year = int(year)
          self.month = int(month)
     
    def date_str(self, day):
          date_obj = datetime.date(self.year, self.month, day)
          date_str = date_obj.strftime(format='%Y-%m-%d')     
          return date_str
            
    def scraper(self, date_str):
            ''' 
            Scrapes JSON object from page using requests module.
            
            Parameters
            - - - - - 
            url : URL string
            hdrs : Header information
            date_str: string in yyyy-mm-dd format
                
            Returns
            - - - -
            dictionary : Returns a JSON dictionary at a given URL.
            
            '''
            params = {'date': date_str}
            page=requests.get(self.url,headers=self.hdrs,params=params)
            dictionary = page.json()
            return dictionary

    def dict_to_df(self, dicti):
         ''' 
         Converts the JSON dictionary into a pandas dataframe
         Appends the dataframe to calendars class attribute         
         
         Parameters
         ----------
         dicti : Output from the scraper method as input.
         
         Returns
         -------
         calendar : Dataframe of stocks with that exdividend date
         
         Appends the dataframe to calendars class attribute
         
         If the date is formatted correctly, it will append a 
         dataframe to the calendars list (class attribute).  
         Otherwise, it will return an empty dataframe.         
         '''
         
         rows = dicti.get('data').get('calendar').get('rows')
         calendar = pandas.DataFrame(rows)
         self.calendars.append(calendar)
         return calendar
   
            
    def calendar(self, day):
          '''
          Combines the scrape and dict_to_df methods
          
          Parameters
          ----------
          day : day of the month as string or number.
          
          Returns
          -------
          dictionary : Returns a JSON dictionary with keys 
          dictionary.keys() => data, message, status
          
          Next Levels: 
          dictionary['data'].keys() => calendar, timeframe
          dictionary['data']['calendar'].keys() => headers, rows
          dictionary['data']['calendar']['headers'] => column names
          dictionary['data']['calendar']['rows'] => dictionary list
    
          '''
          day = int(day)
          date_str = self.date_str(day)      
          dictionary = self.scraper(date_str)
          self.dict_to_df(dictionary)          
          return dictionary
        
year = 2019
month = 1

#get number of days in month
days_in_month = calendar.monthrange(year, month)[1]
#create calendar object    
february = dividend_calendar(year, month)
#define lambda function to iterate over list of days     
function = lambda days: february.calendar(days)

#define list of ints between 1 and the number of days in the month
iterator = list(range(1, days_in_month+1))
#Scrape calendar for each day of the month                    
objects = list(map(function, iterator))
#concatenate all the calendars in the class attribute
concat_df = pandas.concat(february.calendars)

#Drop any rows with missing data
drop_df = concat_df.dropna(how='any')

#set the dataframe's row index to the company name
final_df = drop_df.set_index('companyName')
final_df

,symbol,dividend_Ex_Date,payment_Date,record_Date,dividend_Rate,indicated_Annual_Dividend,announcement_Date
companyName,,,,,,,
ABM Industries Incorporated,ABM,01/02/2019,02/04/2019,01/03/2019,0.180,0.720,12/18/2018
Itau Unibanco Banco Holding SA,ITUB,01/02/2019,02/11/2019,01/03/2019,0.004,0.047,12/20/2018
ESCO Technologies Inc.,ESE,01/02/2019,01/18/2019,01/03/2019,0.080,0.320,11/15/2018
The First of Long Island Corporation,FLIC,01/02/2019,01/14/2019,01/03/2019,0.170,0.680,12/20/2018
First Trust Senior Floating Rate Income Fund II,FCT,01/02/2019,01/15/2019,01/03/2019,0.060,0.720,12/20/2018
...,...,...,...,...,...,...,...
Signet Jewelers Limited,SIG,01/31/2019,03/01/2019,02/01/2019,0.370,1.480,01/17/2019
Teekay Corporation,TK,01/31/2019,02/14/2019,02/01/2019,0.055,0.110,01/08/2019
Teekay LNG Partners L.P.,TGP,01/31/2019,02/08/2019,02/01/2019,0.140,0.560,01/08/2019
Wells Fargo & Company,WFC,01/31/2019,03/01/2019,02/01/2019,0.450,1.800,01/22/2019
"Western Midstream Partners, LP",WES,01/31/2019,02/21/2019,02/01/2019,0.603,2.410,01/22/2019

In [13]:
hdrs =  {'Accept': 'application/json, text/plain, */*',
                 'DNT': "1",
                 'Origin': 'https://www.nasdaq.com/',
                 'Sec-Fetch-Mode': 'cors',
                 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0)'}
url = 'https://www.nasdaq.com/market-activity/stocks/aapl/dividend-history'

import pandas as pd
import requests
from bs4 import BeautifulSoup
page=requests.get(url,headers=hdrs)
soup = BeautifulSoup(page.content, 'html.parser')
# rows = table.findAll(lambda tag: tag.name=='dividend-history__row dividend-history__row--data')
# soup# pd.read_html(page.text)
# print(soup.prettify())
soup.find('thead')

<thead class="dividend-history__table-headings">
<tr class="dividend-history__row dividend-history__row--headings">
<th class="dividend-history__table-heading" scope="col">Ex/EFF DATE</th>
<th class="dividend-history__table-heading" scope="col">TYPE</th>
<th class="dividend-history__table-heading" scope="col">CASH AMOUNT</th>
<th class="dividend-history__table-heading" scope="col">DECLARATION DATE</th>
<th class="dividend-history__table-heading" scope="col">RECORD DATE</th>
<th class="dividend-history__table-heading" scope="col">PAYMENT DATE</th>
</tr>
</thead>

In [67]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

path = "C:\\Users\\bart_\\Desktop\\personal\\code\\trade strategy\\chromedriver_win32\\chromedriver.exe"


chrome_options = Options()
#chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-gpu")
# chrome_options.add_argument("--no-sandbox") # linux only
# chrome_options.add_argument("--headless")
# chrome_options.headless = True # also works
driver = webdriver.Chrome(executable_path=path, options=chrome_options)

In [79]:
ticker = 'aapl'
driver.get(f'https://www.nasdaq.com/market-activity/stocks/{ticker}/dividend-history')
# driver.delete_all_cookies()
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')
dfs = pd.read_html(html)

In [86]:
dfs[0]

   Ex/EFF DATE  TYPE CASH AMOUNT DECLARATION DATE RECORD DATE PAYMENT DATE
0   02/05/2021  CASH      $0.205       01/27/2021  02/08/2021   02/11/2021
1   11/06/2020  CASH      $0.205       10/29/2020  11/09/2020   11/12/2020
2   08/07/2020  CASH       $0.82       07/30/2020  08/10/2020   08/13/2020
3   05/08/2020  CASH       $0.82       04/30/2020  05/11/2020   05/14/2020
4   02/07/2020  CASH       $0.77       01/28/2020  02/10/2020   02/13/2020
..         ...   ...         ...              ...         ...          ...
59  11/17/1989  CASH       $0.11              NaN  11/17/1989          NaN
60  08/21/1989  CASH       $0.10              NaN  08/21/1989          NaN
61  05/22/1989  CASH       $0.10              NaN  05/22/1989          NaN
62  02/17/1989  CASH       $0.10              NaN  02/17/1989          NaN
63  11/21/1988  CASH       $0.10              NaN  11/21/1988          NaN

[64 rows x 6 columns]